import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type QuoteItem = {
  item: string;
  sku: string;
  qty?: number;
  price?: number;
  checked?: boolean;
  isHeader?: boolean;
  isBoldParent?: boolean;
};

const logoUrl =
  "https://media.licdn.com/dms/image/v2/D5616AQGASV7fqDbewg/profile-displaybackgroundimage-shrink_350_1400/profile-displaybackgroundimage-shrink_350_1400/0/1681742630644?e=1772668800&v=beta&t=G-b89nqLk6qiP9TBYM5LlL5WESzhi5l3uldK8ziXkkE";

const loadImage = async (url: string): Promise<string> => {
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.readAsDataURL(blob);
  });
};

const formatDateTime = (d: Date) => {
  try {
    return new Intl.DateTimeFormat("en-GB", {
      dateStyle: "medium",
      timeStyle: "short",
      timeZoneName: "short",
    }).format(d);
  } catch {
    return d.toLocaleString();
  }
};

export async function generateQuotePdf(
  items: QuoteItem[],
  automationEnabled?: boolean,
  validDays = 30,
  currency = "NOK",
) {
  const selected = items.filter((i) => i.checked);
  const subtotal = selected
    .filter((i) => !i.isHeader)
    .reduce((sum, i) => sum + (i.price ?? 0) * (i.qty ?? 1), 0);

  const vat = subtotal * 0.25;
  const total = subtotal + vat;

  const doc = new jsPDF();
  const now = new Date();
  const expiry = new Date(now);
  expiry.setDate(expiry.getDate() + validDays);

  let logoBottomY = 10;
  try {
    const logoData = await loadImage(logoUrl);
    const { width, height } = await new Promise<{ width: number; height: number }>((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ width: img.width, height: img.height });
      img.src = logoData;
    });

    const maxWidth = 180;
    const ratio = height / width;
    const finalWidth = maxWidth;
    const finalHeight = finalWidth * ratio;
    const pageWidth = doc.internal.pageSize.getWidth();
    const x = (pageWidth - finalWidth) / 2;
    const y = 10;

    doc.addImage(logoData, "JPEG", x, y, finalWidth, finalHeight);
    logoBottomY = y + finalHeight;
  } catch {
    // ignore logo failures
  }

  const titleY = logoBottomY + 12;
  doc.setFontSize(20);
  doc.text("Quotation", 14, titleY);

  autoTable(doc, {
    startY: titleY + 12,
    head: [["Item", "SKU", "Qty", `Price (${currency})`, `Line Total (${currency})`]],
    body: selected.map((i) => {
      const qty = i.qty ?? 1;
      const price = i.price ?? 0;
      if (i.isHeader) return [i.item, i.sku, "", "", ""];
      return [i.item, i.sku, qty, price.toFixed(2), (price * qty).toFixed(2)];
    }),
    styles: { fontSize: 10 },
    headStyles: { fillColor: [41, 128, 185] },
    didParseCell: (data) => {
      if (data.section !== "body") return;
      const rowItem = selected[data.row.index];
      if (!rowItem) return;
      if (rowItem.isHeader) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [245, 245, 245];
        return;
      }
      if (rowItem.isBoldParent) data.cell.styles.fontStyle = "bold";
    },
  });

  const tableEndY =
    (doc as any).lastAutoTable?.finalY != null ? (doc as any).lastAutoTable.finalY : titleY + 12;

  const totalsY = tableEndY + 10;
  doc.setFontSize(12);
  doc.text(`Subtotal: ${subtotal.toFixed(2)} ${currency}`, 14, totalsY);
  doc.text(`MVA 25%: ${vat.toFixed(2)} ${currency}`, 14, totalsY + 8);
  doc.text(`Total: ${total.toFixed(2)} ${currency}`, 14, totalsY + 16);

  const qualifiers: string[] = [
    "This document was automatically generated by the online quotation tool.",
    `Generated on: ${formatDateTime(now)}.`,
    ...(!automationEnabled
      ? [
          "Note: Certain automatically suggested dependencies were manually overridden during the preparation of this quotation. This configuration may not be valid and should be independently verified.",
        ]
      : []),
    `This quotation is valid for ${validDays} days from the date of issue.`,
    `Quote expiry date: ${formatDateTime(expiry)}.`,
  ];

  let y = totalsY + 28;
  const bottomMargin = 20;

  if (y > doc.internal.pageSize.getHeight() - bottomMargin - 30) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(200);
  doc.line(14, y - 6, 200, y - 6);

  doc.setFontSize(10);
  doc.setTextColor(80);

  const wrapped = doc.splitTextToSize(qualifiers.join("\n"), 182);
  const estimatedHeight = wrapped.length * 5;

  if (y + estimatedHeight > doc.internal.pageSize.getHeight() - bottomMargin) {
    doc.addPage();
    y = 20;
  }

  doc.text(wrapped, 14, y);
  doc.save("quote.pdf");
}

